Don't run other lint actions on l10n branch

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -10,6 +10,7 @@ jobs:
   lint-frontend:
     name: Lint Frontend
     runs-on: ubuntu-24.04
+    if: github.base_ref != 'l10n_crowdin_translations'
     permissions:
       contents: read
 
@@ -39,50 +40,51 @@ jobs:
           pnpm run biome:validate
 
   lint-translations:
-      name: Lint Translations
-      runs-on: ubuntu-24.04
-      permissions:
-        contents: read
-      steps:
-        - name: Checkout sources
-          uses: actions/checkout@v6
+    name: Lint Translations
+    runs-on: ubuntu-24.04
+    permissions:
+      contents: read
+    steps:
+      - name: Checkout sources
+        uses: actions/checkout@v6
 
-        - name: Setup Node.js
-          uses: actions/setup-node@v6
-          with:
-            node-version: "24"
+      - name: Setup Node.js
+        uses: actions/setup-node@v6
+        with:
+          node-version: "24"
 
-        - name: Setup pnpm
-          uses: pnpm/action-setup@v5
-          with:
-            version: 11
-            run_install: false
+      - name: Setup pnpm
+        uses: pnpm/action-setup@v5
+        with:
+          version: 11
+          run_install: false
 
-        - name: Install frontend dependencies
-          run: |
-            cd frontend
-            pnpm install
+      - name: Install frontend dependencies
+        run: |
+          cd frontend
+          pnpm install
 
-        - name: Check translations
-          run: |
-            cd frontend
-            failed_files=()
-            for file in public/translations/*.json; do
-              echo "Checking $file"
-              pnpm diff:translations "$file" --check || failed_files+=("$file")
+      - name: Check translations
+        run: |
+          cd frontend
+          failed_files=()
+          for file in public/translations/*.json; do
+            echo "Checking $file"
+            pnpm diff:translations "$file" --check || failed_files+=("$file")
+          done
+          if [ ${#failed_files[@]} -gt 0 ]; then
+            echo ""
+            echo "Failed translations:"
+            for f in "${failed_files[@]}"; do
+              echo "  - $f"
             done
-            if [ ${#failed_files[@]} -gt 0 ]; then
-              echo ""
-              echo "Failed translations:"
-              for f in "${failed_files[@]}"; do
-                echo "  - $f"
-              done
-              exit 1
-            fi
+            exit 1
+          fi
 
   lint-backend:
     name: Lint Backend
     runs-on: ubuntu-24.04
+    if: github.base_ref != 'l10n_crowdin_translations'
     permissions:
       contents: read
 
@@ -99,7 +101,7 @@ jobs:
 
       - name: Dummy Frontend Files
         run: mkdir -p frontend/dist && echo "Dummy file" > frontend/dist/index.html
-      
+
       - name: Run cargo fmt
         run: cargo fmt -- --check
 
